### ISSUE TITLE
Hot Keys

### ISSUE THREAD

**Issue by mglodack** [dillonkearns/mobster#21]
It would be amazing if we could get a `?` to display any of the available hot keys.

Keeping the hands at the keyboard is important to me :)

**Comment by dillonkearns** [comment]
I added bolder and more responsive tooltips with the shortcut to the "Start Mobbing" and "Continue" buttons. A design goal of this app is to teach users as they use it rather than as a separate step, and I hope this helps to achieve that.

How does this seem to you? Any other suggestions around this? And thanks for the feedback! 😄 

<img width="1439" alt="mobster_and_1__yarn_start__electron_helper__and_hot_keys_ _issue__21_ _dillonkearns_mobster" src="https://cloud.githubusercontent.com/assets/1384166/23581267/b1b32418-00de-11e7-87c7-2618bbb9a796.png">

**Comment by dillonkearns** [comment]
(By the way, this is available in the latest release)

**Comment by dillonkearns** [comment]
Also added a setting to change the global show/hide shortcut in the config page. Hopefully this makes it a little more discoverable. Open to future improvements, but I'm closing this for now. Feel free to open up another issue with more suggestions!
