### ISSUE TITLE
Setting the shortcut key to a non-ascii crashes the app

### ISSUE THREAD

**Issue by DevL** [dillonkearns/mobster#48]
Version used: 0.33

## Steps to reproduce

1. Enter a non-ASCII key as the shortcut key, e.g. `å`.

## Behaviour

1. The app crashes and keeps crashing on start.

**Comment by dillonkearns** [comment]
Hello @DevL,

So sorry to hear the app is crashing on you! I will work on a fix. For now, you can prevent the app from crashing by running `rm -f *` from the local storage folder. If you're on a Mac, these commands will clear your settings so the app is no longer crashing:

```
cd ~/Library/Application Support/mobster/Local Storage
rm -f *
```

(Otherwise, this directory is `%APPDATA%` on Windows `$XDG_CONFIG_HOME` or `~/.config` on Linux, see https://electron.atom.io/docs/api/app/#appgetpathname).

**Comment by dillonkearns** [comment]
Also @DevL, I'm not sure if the Electron API supports non-ascii shortcuts. Just curious, is it important to your team that you have the shortcut be non-ascii, or would you guys be content with it preventing the crash if you tried?

Thanks for filing the report!

**Comment by dillonkearns** [comment]
@DevL it looks like the Electron API does not support non-ascii characters (here are the valid options: https://electron.atom.io/docs/api/accelerator/). 540c78e6b3f8aa646e6892f473a167696f4d75f1 prevents the crash by ignoring invalid inputs. Thanks again for the report!

**Comment by DevL** [comment]
Thanks for looking into it. It's more of a nuisance and surprising behaviour than anything else. Making sure that the app doesn't crash would be appreciated. :-)

**Comment by dillonkearns** [comment]
@DevL non-ascii characters will no longer crash the be accepted (preventing crashes) as of release 0.0.34 https://github.com/dillonkearns/mobster/releases/tag/v0.0.34. Cheers!
