### ISSUE TITLE
There is no way to use the Researcher role (and others despite driver and navigator)

### ISSUE THREAD

**Issue by DanielMSchmidt** [dillonkearns/mobster#60]
I can't find the setting to enable the researcher role, is there a way to enable it? I see it in the source code, but my elm is to weak to understand what is actually happening.

**Comment by dillonkearns** [comment]
Hey there!

So the way I designed it is that it unlocks the level 2 roles once you gain enough experience. Right now, you gain experience by checking off 3 boxes in at least one role. Hope that helps!

Any feedback you have is welcome 😄

**Comment by DanielMSchmidt** [comment]
Cool, good to know 👍 I would love to have a flag for that, we had a mob programming on a spec implementation, so we needed someone for researching 😇 

Thank you for taking the time to answer :)

**Comment by dillonkearns** [comment]
Hey Daniel, happy to clarify things!

The intention of the mob RPG game is actually to be used as a learning tool rather than to keep track of those roles. From my experience mobbing, the researcher role is an organic thing that anyone who is not in the driver role can take on. By practicing using those roles with the RPG game, it can become more natural to reach for that role in the real world.

I think it would get pretty confusing if I tried to support the RPG game as a tool to be used outside of a learning exercise. And I worry that it would clutter the experience for most users and make it more complicated.
