### ISSUE TITLE
Feature Request: Ability to Pause

### ISSUE THREAD

**Issue by aknobloch** [dillonkearns/mobster#62]
Self-explanatory title, it would be nice to have an option to pause the current user's timer. Bonus points if a shortcut was introduced, too :)

**Comment by dillonkearns** [comment]
Hello! This is one of those things where not having a feature can also be seen as a feature. In this case, I really wanted Mobster to help build the types of behaviors that really help teams mob or pair effectively. And one of the things I saw using other tools for mob timers was that pausing led to a sort of attachment to "my time". I found that by not having a timer, the mob forgets about whose turn it is and just gives in instead of trying to remember to pause it when a whiteboard discussion starts, etc. On the net, it's random so anybody is as likely as anyone else to have a discussion while they're at the keyboard. So I've found that it really helps let go of that by just not having the feature at all so you don't have to think about it.

You could definitely argue for wanting to pause in certain situations, but I think that the benefits outweigh the cons for me, at least as far as the goals of this app are concerned.

Thanks for starting the discussion! I hope that helps clarify the underlying philosophy behind that design decision.
